# Generated by Django 5.1.6 on 2025-04-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solsub', '0003_cluster_trial_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='cluster_timeline',
        ),
        migrations.AddField(
            model_name='cluster',
            name='timeline_days',
            field=models.IntegerField(default=30),
        ),
    ]
