# Generated by Django 5.1.6 on 2025-04-14 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solsub', '0004_remove_cluster_cluster_timeline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='timeline_days',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='trial_period',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
